[bar]
background = "#1a1b26"
background-alpha = 1.0
text = "#ffffff"
active = "#36cbe7"
size-horizontal = 32
size-vertical = 40
icon-slot = 26
icon-canvas = 18
icon-font = 14
status-slot = 22

[popups]
background = "#1a1b26"
background-alpha = 1.0
text = "#ffffff"
border = "#36cbe7"
border-alpha = 1.0

[tooltip]
background = "#1a1b26"
text = "#ffffff"
border = "#36cbe7"

[menu]
background = "#1a1b26"
text = "#ffffff"
border = "#36cbe7"
selected-text = "#36cbe7"

[font]
base-size = 13

[controls]
normal-border-width = 1
hover-cursor-border-width = 1
focus-color = "#36cbe7"
selected-color = "#36cbe7"
hover-cursor-color = "#36cbe7"
