hl.on("hyprland.start", function()
	hl.exec_cmd("pipewire")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
	hl.exec_cmd("/usr/libexec/polkit-kde-authentication-agent-1")

	hl.exec_cmd("elephant")
	hl.exec_cmd("mako")
	hl.exec_cmd("waybar --config ~/.config/waybar/config --style ~/.config/waybar/theme/waybar.css")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("bash -c 'sleep 0.5 && awww img ~/.local/share/fuzi/background'")
	hl.exec_cmd("bitwarden")

	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark'")
end)
