allow_remote_control yes
confirm_os_window_close 0
cursor_shape block
enable_audio_bell no
hide_window_decorations yes
include ~/.config/kitty/theme/kitty.conf
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
window_padding_width 14


